name: EV Range Prediction CD


on:
  push:
    branches:
      - main


env:
  PROJECT_ID: project-29042adf-275b-46cc-a25
  REGION: europe-west3
  REPOSITORY: ev-range-images
  IMAGE_NAME: ev-range-prediction


jobs:

  deploy:

    runs-on: ubuntu-latest


    permissions:
      contents: read
      id-token: write


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: github-actions@project-29042adf-275b-46cc-a25.iam.gserviceaccount.com


    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2


    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev


    - name: Build Docker Image
      run: |

        docker build \
        -t europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .


    - name: Push Docker Image
      run: |

        docker push \
        europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}


    - name: Deploy to Cloud Run
      run: |

        gcloud run deploy ev-range-prediction \
        --image europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
        --region ${{ env.REGION }} \
        --platform managed \
        --memory 2Gi \
        --cpu 1 \
        --allow-unauthenticated